language: node_js
node_js:
  - node
cache: npm

install: 
  -npm install
  -npm ci

script: 
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  on:
    branch: gh-pages

