language: node_js
node_js:
  - "15"  

cache: yarn

install: 
  - yarn install

script: 
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main

