language: node_js
  
cache: yarn

node_js:
  - "15"

install: 
  -yarn install

script: 
  - yarn run test
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main

