language: node_js
  
cache: npm

node_js:
  - "15"

script: 
  - npm install
  - npm run test
  - npm start
  - npm run build
  

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main