language: node_js
  
cache: npm

node_js:
  - 12

install: 
  -npm ci

script: 
  - npm install
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  on:
    branch: gh-pages

